[package]
name = "pylon-token"
version = "0.2.0"
authors = ["carter@pylon.money", "Terraform Labs, PTE."]
edition = "2018"
description = "Common helpers for other pylon-token specs"
license = "Apache-2.0"
repository = "https://github.com/pylon-protocol/pylon-token-contracts"
homepage = "https://pylon.money"
documentation = "https://docs.pylon.money"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cw2 = { version = "0.14.0" }
cw20 = { version = "0.14.0" }
cosmwasm-std = { version = "1.0.0", features = ["iterator"] }
cosmwasm-storage = { version = "1.0.0", features = ["iterator"] }
classic-bindings = { version = "0.1.1" }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }

[profile.dev]
overflow-checks = true

[profile.release]
overflow-checks = true
