[package]
name = "glow"
version = "0.2.0"
authors = ["Spectrum"]
edition = "2018"
description = "Interface to lp and gov contracts"
license = "Apache-2.0"
repository = "https://github.com/orionterra/staking-terra"
homepage = "https://orion.money"
documentation = ""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cw20 = { version = "0.14.0" }
cosmwasm-std = { version = "1.0.0" }
cosmwasm-storage = { version = "1.0.0" }
classic-bindings = { version = "0.1.1" }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }

[profile.dev]
overflow-checks = true

[profile.release]
overflow-checks = true
